(defvar mnx::*config-paths*
  '(("emacs/config.el" . "/home/semi/.config/emacs/config.el")
    ("emacs/early-init.el" . "/home/semi/.config/emacs/early-init.el")
    ("emacs/init.el" . "/home/semi/.config/emacs/init.el")
    ("emacs/config.el" . "/home/semi/.config/emacs/config.el")
    ("emacs/org.el" . "/home/semi/.config/emacs/org.el")
    ("emacs/functions.el" . "/home/semi/.config/emacs/functions.el")
    ("emacs/elpaca.el" . "/home/semi/.config/emacs/elpaca.el")

    ("configs/tofi.conf" . "/home/semi/.config/tofi.conf")
    ("configs/yambar.yml" . "/home/semi/.config/yambar/config.yml")
    ("configs/config.fish" . "/home/semi/.config/fish/config.fish")
    ("configs/alacritty.toml" . "/home/semi/.config/alacritty.toml")
    ("configs/foot.ini" . "/home/semi/.config/foot/foot.ini")
    ("configs/river" . "/home/semi/.config/river/init")
    ("configs/profile" . "/home/semi/.profile")))
