base_font: &base_font Iosevka Nerd Font:pixelsize=14
bg_default: &bg_default {stack: [{background: {color: 181825ff}}, {underline: {size: 4, color: b4befeff}}]}
bar:
  height: 20
  location: top
  font: base_font
  spacing: 10
  margin: 10
  layer: bottom
  foreground: cdd6f4ff
  background: 181825ff

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: , font: *base_font}}
              conditions:
                id == 1: {string: {text: , font: *base_font}}
                id == 2: {string: {text: , font: *base_font}}
                id == 3: {string: {text: , font: *base_font}}
                id == 4: {string: {text: , font: *base_font}}
                id == 7: {string: {text: , font: *base_font}}
                id == 8: {string: {text: , font: *base_font}}
                id == 9: {string: {text: , font: *base_font}}
                id == 10: {string: {text: "scratchpad", font: *base_font}}
                id == 11: {string: {text: "work", font: *base_font}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: f38ba8ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: 313244ff}}
  right:
    - network:
        poll-interval: 2000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == enp8s0:
                map:
                  default: {string: {text: , font: *base_font, right-margin: 10}}
                  conditions:
                    state == down: {string: {text: , font: *base_font, right-margin: 10}}
                    state == up:
                      map:
                        default:
                          - string: {text: , font: *base_font, right-margin: 10}
                          - string: {text: "{dl-speed:mb}/{ul-speed:mb} Mb/s"}

                        conditions:
                          ipv4 == "":
                            - string: {text: , font: *base_font, right-margin: 10}
                            - string: {text: "{dl-speed:mb}/{ul-speed:mb} Mb/s"}
    - clock:
        content:
          - string: {text: , font: *base_font, right-margin: 10}
          - string: {text: "{date}", right-margin: 10}
          - string: {text: , font: *base_font, right-margin: 10}
          - string: {text: "{time}"}
